### ISSUE TITLE
feat: need a wrapper to use ydb in a more simple way

### ISSUE THREAD

**Issue by pav5000** [yandex-cloud/ydb-go-sdk#5]
# Feature Request

**Describe the Feature Request**

The current version of SDK needs a lot of boilerplate code just to make a simple db request. This is very unconvenient.
For example, if I want to select some data from a table in serverless function, I need about 30-40 lines to correctly init the db connection and another 60 lines to store the ydb certificate in a const. Also, to get to this point you should read a lot of documentation about details of sessions, connections, certificate, etc... I'm still not sure if I got it right.
The majority of users needs one simple function to init a db client. Without any boilerplate code.
https://github.com/yandex-cloud/ydb-go-sdk/blob/master/example/basic_example/series.go
The basic example here contains 472 lines, 472, Carl! It's CRAZY!

**Describe Preferred Solution**
I suggest to add some simple functions specially for serverless functions and code which runs inside compute cloud vms.
Here is a sketch of how it may look like:
1. `func New(ctx context.Context, endpoint, path string) (*Client, error)`
creates db client with a session pool and all needed certificates and boilerplate code. It also should get IAM token automatically from serverless function environment or compute cloud environment (also include a fallback to some static iam from env vars or the way yc util gets it to be able to run the code on a local machine).

2. `func (c *Client) Execute(ctx context.Context, query string, params *QueryParameters, opts ...ExecuteDataQueryOption)(*Result, error)`
Executes the query and returns the result.
Without any headache with sessions and transaction control.

3. `func (c *Client) GetSession(context.Context) (*Session, error)`
Returns a session from pool which is ready to take queries.
For folks who want more control over execution and willing to use transactions.

**Additional Context**

The main idea is to simplify usage of YDB for beginners and reduce errors in boilerplate. It's too frightening now.
You also may get reduced amount of support tickets. I myself created at least 2 tickets till got my db init code working.

**If the feature request is approved, would you be willing to submit a PR?**
No
I'm not sure I got the concepts right, so it would be better for ydb developers to provide the right solution.
Here is my current wrapper that inits db and provides sessions, maybe it'll help to get the idea: https://github.com/pav5000/easy-yc/blob/main/db/ydb.go

**Comment by asmyasnikov** [comment]
Hi!
Ydb SDK is in migrating stage to github.com/ydb-platform/ydb-go-sdk
We are changed many API interfaces for:
- easy usage
- hide some code and settings for discard wrong usage of driver
- split package for different ydb use-cases (inside yandex-cloud and outside)
- provide pluginization over ydb-go-sdk
- and some features
Currently we are testing stability before publish release v3.0.0
I seen your repo early. After release v3 I will create PR to your repository with actual changes

**Comment by asmyasnikov** [comment]
https://github.com/ydb-platform/ydb-go-sdk
